spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: Postgre@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  security:
    jwt:
      secret: your_secret_key
      expiration: 3600000 # 1 hour
  config:
    activate:
      on-profile: prod

logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}